### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TomCJones**
I guess that you wanted to retain control. I thought I would try to see if you accept the concept of a external source issuing a rekey event. Given what happened yesterday, it is not clear to me that the core would accept the idea that user's need to be able to regain access to their identifier.

### CODE REVIEW

**Comment by peacekeeper** [comment]
+1 to clearly distinguishing between recovering the old key, and recovering an identifier by creating a new key! We should have been more precise about this from the beginning.

I'm not sure however if it's true that there is always some kind of "super-user", what does this mean exactly?

**Comment by SmithSamuelM** [comment]
Historically. Key rotation required an administrator or super user who held the rotation keys.  This causes a disconnect with decentralized identity which has no facility for a super user.  So these old concepts for rotation don't fit anymore.  Uport had a smart contract which a rotation key.  KERI does pre-rotation. Many other DiD methods have no support for key rotation.

**Comment by TomCJones** [comment]
So, one thinks its ok, the other not?  This is what i need to understand before i commit to anything like KERI. If you are saying there is no possible compliant method by which a user can recover a ID once it is lost, then I will need to find a place that treats users better than that.

**Comment by SmithSamuelM** [comment]
@TomCJones 

I am not sure what you mean by treating user better than that. The identifiers in KERI AID (autonomic identifiers) are long pseudo-random strings of characters. They are used as a root of trust.  One use of AIDs is to provide a root of trust for some other human meaningful identifier.  The process by which a human meaningful identifier is associated with or comes under the aegis of some AID is dependent on the human meaningful identifier. One could have a manual process for changing that association from one AID to another.

Key rotation that is not locked down is insecure. The bane of identity systems in general is that key rotation was not locked down.

Association of any identifier with a natural person is a process in its own right. KERI does not constrain how one makes the association between an AID and a natural person.

Because an AID is a cryptographic identifier uniquely derived from a set of public keys, there are two ways to do key rotation. 

1) Rotate the authoritative keys for the AID using a key event that is provable via  a key event log. (Micro ledger, identifier specific blockchain)

2) Create an new identifier which comes with a new set of keys.


In either 1) or 2) one must still make association of the AID to a natural person.  These association as may use some type of authentication method, hopefully multi-factor. The idea is that there is a multi-factor association. 

So ultimately if one loses control of an AID (which is easy if one is stupid and shares private keys or very difficult if not practically impossible if one protects ones private keys well). then one abandons the AID, creates a new one and then makes associations to the new AID.  It is functionally equivalent.


What I believe you are missing is the fact that when one rotates keys in a token based identity system all tokens issued under the old keys are immediately effectively revoked. This is equivalent to abandoning an identifier as all issuances have to reissued.

So at least in KERI you have the opportunity to have much more persistence of issuances given the enhanced security of key rotation. But ultimately the recourse ends up being the same. It's about reissuance policy. How does key rotation affect reissuance. It's not taking care of the user any better if you have forced reissuance.

**Comment by peacekeeper** [comment]
@TomCJones did you mean to close this PR? Based on [yesterday's ID WG call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#meeting---21-dec-2020---1400-et-recording), I am thinking perhaps it was closed by accident and we should re-open it?

**Pull request closed without merging**
